---
title: DR Ungkarn Jarujareet
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
logo: logo.jpg
include:
- img
github: is\_project\_page:false
social-network-links:
  email: ungakarn.jarujareet@nectec.or.th
theme: jekyll-theme-minimal
