---
title: DR Ungkarn Jarujareet
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
logo: logo.jpg
github: is\_project\_page:false
theme: jekyll-theme-minimal


<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-0BJSZGZBR0"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-0BJSZGZBR0');
</script>
