---
title: DR Ungkarn Jarujareet
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
logo: logo.jpg
github:
  is_project_page: false
social-network-links:
  email: ungakarn.jarujareet@nectec.or.th
theme: jekyll-theme-minimal
