---
title: DR Ungkarn Jarujareet
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
logo: logo.jpg
github: is\_project\_page:false
theme: jekyll-theme-minimal
plugins:
- jekyll-seo-tag
