---
title: DR Ungkarn Jarujareet
timezone: UTC
logo: /assets/logo.jpg
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
social-network-links:
  email: ungakarn.jarujareet@nectec.or.th
theme: jekyll-theme-minimal
